# Generated by Django 5.1.3 on 2024-11-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
