# Generated by Django 5.1.3 on 2024-11-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
